using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MealPlanner.Api.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddUserRecipePrefModifiers : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // All guards use IF EXISTS / IF NOT EXISTS so this migration is safe
            // to run against a DB that was created with the full schema directly.

            migrationBuilder.Sql(@"DROP INDEX IF EXISTS ""IX_WeekMealSlots_WeekId_DayOfWeek_MealType"";");

            migrationBuilder.Sql(@"ALTER TABLE ""WeekMealSlots"" ADD COLUMN IF NOT EXISTS ""Position"" integer NOT NULL DEFAULT 0;");

            migrationBuilder.Sql(@"ALTER TABLE ""WeekMealSlots"" ADD COLUMN IF NOT EXISTS ""SelectedModifierIngredientIds"" jsonb NOT NULL DEFAULT '[]';");

            migrationBuilder.Sql(@"ALTER TABLE ""Users"" ADD COLUMN IF NOT EXISTS ""HeightInches"" integer NOT NULL DEFAULT 0;");

            migrationBuilder.Sql(@"ALTER TABLE ""Users"" ADD COLUMN IF NOT EXISTS ""WeightPounds"" numeric NOT NULL DEFAULT 0;");

            migrationBuilder.Sql(@"ALTER TABLE ""UserRecipePrefs"" ADD COLUMN IF NOT EXISTS ""SelectedModifierIngredientIds"" jsonb NOT NULL DEFAULT '[]';");

            migrationBuilder.Sql(@"ALTER TABLE ""RecipeSteps"" ADD COLUMN IF NOT EXISTS ""LinkedIngredientIds"" jsonb NOT NULL DEFAULT '[]';");

            migrationBuilder.Sql(@"ALTER TABLE ""RecipeSteps"" ADD COLUMN IF NOT EXISTS ""PrepCategory"" text NOT NULL DEFAULT '';");

            migrationBuilder.Sql(@"ALTER TABLE ""RecipeSteps"" ADD COLUMN IF NOT EXISTS ""ScaleByLinkedIngredients"" boolean NOT NULL DEFAULT false;");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""UserIngredientPrefs"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""UserId"" integer NOT NULL,
                    ""IngredientId"" integer NOT NULL,
                    ""IsFavorite"" boolean NOT NULL,
                    ""LastUsedAt"" timestamp with time zone,
                    CONSTRAINT ""FK_UserIngredientPrefs_Ingredients_IngredientId"" FOREIGN KEY (""IngredientId"") REFERENCES ""Ingredients""(""Id"") ON DELETE CASCADE,
                    CONSTRAINT ""FK_UserIngredientPrefs_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users""(""Id"") ON DELETE CASCADE
                );");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""UserWeekPrefs"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""UserId"" integer NOT NULL,
                    ""WeekId"" integer NOT NULL,
                    ""IsFavorite"" boolean NOT NULL,
                    CONSTRAINT ""FK_UserWeekPrefs_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users""(""Id"") ON DELETE CASCADE,
                    CONSTRAINT ""FK_UserWeekPrefs_Weeks_WeekId"" FOREIGN KEY (""WeekId"") REFERENCES ""Weeks""(""Id"") ON DELETE CASCADE
                );");

            migrationBuilder.Sql(@"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_WeekMealSlots_WeekId_DayOfWeek_MealType_Position"" ON ""WeekMealSlots"" (""WeekId"", ""DayOfWeek"", ""MealType"", ""Position"");");

            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_UserIngredientPrefs_IngredientId"" ON ""UserIngredientPrefs"" (""IngredientId"");");

            migrationBuilder.Sql(@"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_UserIngredientPrefs_UserId_IngredientId"" ON ""UserIngredientPrefs"" (""UserId"", ""IngredientId"");");

            migrationBuilder.Sql(@"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_UserWeekPrefs_UserId_WeekId"" ON ""UserWeekPrefs"" (""UserId"", ""WeekId"");");

            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_UserWeekPrefs_WeekId"" ON ""UserWeekPrefs"" (""WeekId"");");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "UserIngredientPrefs");

            migrationBuilder.DropTable(
                name: "UserWeekPrefs");

            migrationBuilder.DropIndex(
                name: "IX_WeekMealSlots_WeekId_DayOfWeek_MealType_Position",
                table: "WeekMealSlots");

            migrationBuilder.DropColumn(
                name: "Position",
                table: "WeekMealSlots");

            migrationBuilder.DropColumn(
                name: "SelectedModifierIngredientIds",
                table: "WeekMealSlots");

            migrationBuilder.DropColumn(
                name: "HeightInches",
                table: "Users");

            migrationBuilder.DropColumn(
                name: "WeightPounds",
                table: "Users");

            migrationBuilder.DropColumn(
                name: "SelectedModifierIngredientIds",
                table: "UserRecipePrefs");

            migrationBuilder.DropColumn(
                name: "LinkedIngredientIds",
                table: "RecipeSteps");

            migrationBuilder.DropColumn(
                name: "PrepCategory",
                table: "RecipeSteps");

            migrationBuilder.DropColumn(
                name: "ScaleByLinkedIngredients",
                table: "RecipeSteps");

            migrationBuilder.CreateIndex(
                name: "IX_WeekMealSlots_WeekId_DayOfWeek_MealType",
                table: "WeekMealSlots",
                columns: new[] { "WeekId", "DayOfWeek", "MealType" },
                unique: true);
        }
    }
}
