// <auto-generated />
using System;
using MealPlanner.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MealPlanner.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MealPlanner.Api.Models.FridgeDepletionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DepletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FridgeItemId")
                        .HasColumnType("integer");

                    b.Property<bool>("OverriddenByUser")
                        .HasColumnType("boolean");

                    b.Property<decimal>("QuantityUsed")
                        .HasColumnType("numeric");

                    b.Property<bool>("WasAssumed")
                        .HasColumnType("boolean");

                    b.Property<int>("WeekMealSlotId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FridgeItemId");

                    b.HasIndex("WeekMealSlotId");

                    b.ToTable("FridgeDepletionLogs");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.FridgeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddedVia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HouseholdId")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsLeftover")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PurchasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<int?>("SourceRecipeId")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("HouseholdId", "ExpiresAt");

                    b.HasIndex("HouseholdId", "Location");

                    b.ToTable("FridgeItems");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.GroceryList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HouseholdId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WeekId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("WeekId")
                        .IsUnique();

                    b.ToTable("GroceryLists");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.GroceryListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AddedToFridge")
                        .HasColumnType("boolean");

                    b.Property<int>("GroceryListId")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PlannedQuantity")
                        .HasColumnType("numeric");

                    b.Property<string>("PlannedUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("PurchasedQuantity")
                        .HasColumnType("numeric");

                    b.Property<string>("RecipeIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("StoreSection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroceryListId");

                    b.HasIndex("IngredientId");

                    b.ToTable("GroceryListItems");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.Household", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Households");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.HouseholdPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CuisinePreferences")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("DefaultCookTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DefaultPrepStyle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DietaryRestrictions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("DislikedIngredients")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("HouseholdId")
                        .HasColumnType("integer");

                    b.Property<string>("MyPlateTargets")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId")
                        .IsUnique();

                    b.ToTable("HouseholdPreferences");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aliases")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("DefaultLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FoodGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsFlexibleGroup")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMyPlateCounted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPerishable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStaple")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PackageSizeUnit")
                        .HasColumnType("text");

                    b.Property<string>("PurchaseUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ServingSize")
                        .HasColumnType("numeric");

                    b.Property<string>("ServingUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ShelfLifeDays")
                        .HasColumnType("integer");

                    b.Property<string>("StoreSection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("TypicalPackageSize")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.PrepSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("PrepDay")
                        .HasColumnType("date");

                    b.Property<string>("SheetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("WeekId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WeekId");

                    b.ToTable("PrepSheets");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.PrepSheetStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int>("ParallelGroup")
                        .HasColumnType("integer");

                    b.Property<int>("PrepSheetId")
                        .HasColumnType("integer");

                    b.Property<string>("RecipeNameContext")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RecipeStepId")
                        .HasColumnType("integer");

                    b.Property<int>("StartOffsetMinutes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PrepSheetId");

                    b.HasIndex("RecipeStepId");

                    b.ToTable("PrepSheetSteps");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseYieldServings")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cuisine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FoodGroupServings")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("HouseholdId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsCookFreshOnly")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFreezerFriendly")
                        .HasColumnType("boolean");

                    b.Property<string>("MealTypeTags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrepStyleTag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScalabilityTag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text");

                    b.Property<string>("TimeTag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Cuisine");

                    b.HasIndex("HouseholdId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsModifier")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<string>("SubstituteIngredientIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.RecipeStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPassive")
                        .HasColumnType("boolean");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer");

                    b.Property<string>("TimingTag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId", "StepNumber");

                    b.ToTable("RecipeSteps");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.SnackSuggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FoodGroupTarget")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean");

                    b.Property<string>("SuggestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UsesFridgeItemId")
                        .HasColumnType("integer");

                    b.Property<int>("WeekId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WeekId");

                    b.ToTable("SnackSuggestions");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HouseholdId")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("HouseholdId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.UserRecipePref", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HouseholdId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDisliked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("HouseholdId", "RecipeId")
                        .IsUnique();

                    b.ToTable("UserRecipePrefs");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.Week", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HouseholdId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsInRotation")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSavedTemplate")
                        .HasColumnType("boolean");

                    b.Property<string>("MaxCookTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrepStyle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TemplateName")
                        .HasColumnType("text");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.ToTable("Weeks");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.WeekMealSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AssumedCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEatingOut")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSkipped")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("MarkedSkippedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<int>("ServingsPlanned")
                        .HasColumnType("integer");

                    b.Property<int>("WeekId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("WeekId", "DayOfWeek", "MealType")
                        .IsUnique();

                    b.ToTable("WeekMealSlots");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.FridgeDepletionLog", b =>
                {
                    b.HasOne("MealPlanner.Api.Models.FridgeItem", "FridgeItem")
                        .WithMany("DepletionLogs")
                        .HasForeignKey("FridgeItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPlanner.Api.Models.WeekMealSlot", "WeekMealSlot")
                        .WithMany("DepletionLogs")
                        .HasForeignKey("WeekMealSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FridgeItem");

                    b.Navigation("WeekMealSlot");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.FridgeItem", b =>
                {
                    b.HasOne("MealPlanner.Api.Models.Household", "Household")
                        .WithMany("FridgeItems")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPlanner.Api.Models.Ingredient", "Ingredient")
                        .WithMany("FridgeItems")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.GroceryList", b =>
                {
                    b.HasOne("MealPlanner.Api.Models.Household", "Household")
                        .WithMany("GroceryLists")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPlanner.Api.Models.Week", "Week")
                        .WithOne("GroceryList")
                        .HasForeignKey("MealPlanner.Api.Models.GroceryList", "WeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");

                    b.Navigation("Week");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.GroceryListItem", b =>
                {
                    b.HasOne("MealPlanner.Api.Models.GroceryList", "GroceryList")
                        .WithMany("Items")
                        .HasForeignKey("GroceryListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPlanner.Api.Models.Ingredient", "Ingredient")
                        .WithMany("GroceryListItems")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroceryList");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.HouseholdPreferences", b =>
                {
                    b.HasOne("MealPlanner.Api.Models.Household", "Household")
                        .WithOne("Preferences")
                        .HasForeignKey("MealPlanner.Api.Models.HouseholdPreferences", "HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.PrepSheet", b =>
                {
                    b.HasOne("MealPlanner.Api.Models.Week", "Week")
                        .WithMany("PrepSheets")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Week");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.PrepSheetStep", b =>
                {
                    b.HasOne("MealPlanner.Api.Models.PrepSheet", "PrepSheet")
                        .WithMany("Steps")
                        .HasForeignKey("PrepSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPlanner.Api.Models.RecipeStep", "RecipeStep")
                        .WithMany("PrepSheetSteps")
                        .HasForeignKey("RecipeStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrepSheet");

                    b.Navigation("RecipeStep");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.Recipe", b =>
                {
                    b.HasOne("MealPlanner.Api.Models.Household", "Household")
                        .WithMany("Recipes")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.RecipeIngredient", b =>
                {
                    b.HasOne("MealPlanner.Api.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPlanner.Api.Models.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.RecipeStep", b =>
                {
                    b.HasOne("MealPlanner.Api.Models.Recipe", "Recipe")
                        .WithMany("Steps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.SnackSuggestion", b =>
                {
                    b.HasOne("MealPlanner.Api.Models.Week", "Week")
                        .WithMany("SnackSuggestions")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Week");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.User", b =>
                {
                    b.HasOne("MealPlanner.Api.Models.Household", "Household")
                        .WithMany("Users")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.UserRecipePref", b =>
                {
                    b.HasOne("MealPlanner.Api.Models.Household", "Household")
                        .WithMany("RecipePrefs")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPlanner.Api.Models.Recipe", "Recipe")
                        .WithMany("UserPreferences")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.Week", b =>
                {
                    b.HasOne("MealPlanner.Api.Models.Household", "Household")
                        .WithMany("Weeks")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.WeekMealSlot", b =>
                {
                    b.HasOne("MealPlanner.Api.Models.Recipe", "Recipe")
                        .WithMany("MealSlots")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MealPlanner.Api.Models.Week", "Week")
                        .WithMany("MealSlots")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("Week");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.FridgeItem", b =>
                {
                    b.Navigation("DepletionLogs");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.GroceryList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.Household", b =>
                {
                    b.Navigation("FridgeItems");

                    b.Navigation("GroceryLists");

                    b.Navigation("Preferences");

                    b.Navigation("RecipePrefs");

                    b.Navigation("Recipes");

                    b.Navigation("Users");

                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.Ingredient", b =>
                {
                    b.Navigation("FridgeItems");

                    b.Navigation("GroceryListItems");

                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.PrepSheet", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.Recipe", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("MealSlots");

                    b.Navigation("Steps");

                    b.Navigation("UserPreferences");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.RecipeStep", b =>
                {
                    b.Navigation("PrepSheetSteps");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.Week", b =>
                {
                    b.Navigation("GroceryList");

                    b.Navigation("MealSlots");

                    b.Navigation("PrepSheets");

                    b.Navigation("SnackSuggestions");
                });

            modelBuilder.Entity("MealPlanner.Api.Models.WeekMealSlot", b =>
                {
                    b.Navigation("DepletionLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
