begin;

create table if not exists "__EFMigrationsHistory" (
  "MigrationId" character varying(150) not null,
  "ProductVersion" character varying(32) not null,
  constraint "PK___EFMigrationsHistory" primary key ("MigrationId")
);

create table if not exists "Households" (
  "Id" integer generated by default as identity primary key,
  "Name" text not null,
  "Size" integer not null,
  "CreatedAt" timestamp with time zone not null,
  "UpdatedAt" timestamp with time zone not null,
  "Timezone" text not null
);

create table if not exists "Ingredients" (
  "Id" integer generated by default as identity primary key,
  "Name" text not null,
  "FoodGroup" text not null,
  "ServingSize" numeric not null,
  "ServingUnit" text not null,
  "PurchaseUnit" text not null,
  "DefaultLocation" text not null,
  "StoreSection" text not null,
  "IsPerishable" boolean not null,
  "IsFlexibleGroup" boolean not null,
  "IsMyPlateCounted" boolean not null,
  "ShelfLifeDays" integer not null,
  "TypicalPackageSize" numeric null,
  "PackageSizeUnit" text null,
  "IsStaple" boolean not null,
  "Aliases" jsonb not null,
  "Notes" text null
);

create table if not exists "HouseholdPreferences" (
  "Id" integer generated by default as identity primary key,
  "HouseholdId" integer not null,
  "DietaryRestrictions" jsonb not null,
  "DislikedIngredients" jsonb not null,
  "CuisinePreferences" jsonb not null,
  "DefaultCookTime" text not null,
  "DefaultPrepStyle" text not null,
  "MyPlateTargets" jsonb null,
  "UpdatedAt" timestamp with time zone not null,
  constraint "FK_HouseholdPreferences_Households_HouseholdId"
    foreign key ("HouseholdId") references "Households" ("Id") on delete cascade
);

create table if not exists "Recipes" (
  "Id" integer generated by default as identity primary key,
  "HouseholdId" integer not null,
  "Name" text not null,
  "Cuisine" text not null,
  "ScalabilityTag" text not null,
  "TimeTag" text not null,
  "PrepStyleTag" text not null,
  "IsFreezerFriendly" boolean not null,
  "IsCookFreshOnly" boolean not null,
  "BaseYieldServings" integer not null,
  "MealTypeTags" jsonb not null,
  "ImageUrl" text null,
  "SourceUrl" text null,
  "FoodGroupServings" jsonb not null,
  "CreatedAt" timestamp with time zone not null,
  constraint "FK_Recipes_Households_HouseholdId"
    foreign key ("HouseholdId") references "Households" ("Id") on delete cascade
);

create table if not exists "Users" (
  "Id" integer generated by default as identity primary key,
  "HouseholdId" integer not null,
  "Email" text not null,
  "DisplayName" text not null,
  "Age" integer not null,
  "Sex" text not null,
  "ActivityLevel" text not null,
  "Role" text not null,
  "CreatedAt" timestamp with time zone not null,
  "PasswordHash" text not null,
  constraint "FK_Users_Households_HouseholdId"
    foreign key ("HouseholdId") references "Households" ("Id") on delete cascade
);

create table if not exists "Weeks" (
  "Id" integer generated by default as identity primary key,
  "HouseholdId" integer not null,
  "WeekStartDate" date not null,
  "Status" text not null,
  "PrepStyle" text not null,
  "MaxCookTime" text not null,
  "IsSavedTemplate" boolean not null,
  "TemplateName" text null,
  "IsInRotation" boolean not null,
  "CreatedAt" timestamp with time zone not null,
  constraint "FK_Weeks_Households_HouseholdId"
    foreign key ("HouseholdId") references "Households" ("Id") on delete cascade
);

create table if not exists "FridgeItems" (
  "Id" integer generated by default as identity primary key,
  "HouseholdId" integer not null,
  "IngredientId" integer not null,
  "Quantity" numeric not null,
  "Unit" text not null,
  "Location" text not null,
  "PurchasedAt" timestamp with time zone null,
  "ExpiresAt" timestamp with time zone null,
  "IsLeftover" boolean not null,
  "SourceRecipeId" integer null,
  "AddedVia" text not null,
  constraint "FK_FridgeItems_Households_HouseholdId"
    foreign key ("HouseholdId") references "Households" ("Id") on delete cascade,
  constraint "FK_FridgeItems_Ingredients_IngredientId"
    foreign key ("IngredientId") references "Ingredients" ("Id") on delete cascade
);

create table if not exists "RecipeIngredients" (
  "Id" integer generated by default as identity primary key,
  "RecipeId" integer not null,
  "IngredientId" integer not null,
  "Quantity" numeric not null,
  "Unit" text not null,
  "IsModifier" boolean not null,
  "IsOptional" boolean not null,
  "SubstituteIngredientIds" jsonb not null,
  "Notes" text null,
  constraint "FK_RecipeIngredients_Ingredients_IngredientId"
    foreign key ("IngredientId") references "Ingredients" ("Id") on delete cascade,
  constraint "FK_RecipeIngredients_Recipes_RecipeId"
    foreign key ("RecipeId") references "Recipes" ("Id") on delete cascade
);

create table if not exists "RecipeSteps" (
  "Id" integer generated by default as identity primary key,
  "RecipeId" integer not null,
  "StepNumber" integer not null,
  "Instruction" text not null,
  "TimingTag" text not null,
  "DurationMinutes" integer not null,
  "IsPassive" boolean not null,
  constraint "FK_RecipeSteps_Recipes_RecipeId"
    foreign key ("RecipeId") references "Recipes" ("Id") on delete cascade
);

create table if not exists "UserRecipePrefs" (
  "Id" integer generated by default as identity primary key,
  "HouseholdId" integer not null,
  "RecipeId" integer not null,
  "IsFavorite" boolean not null,
  "IsDisliked" boolean not null,
  "SelectedModifierIngredientIds" jsonb not null,
  "LastUsedAt" timestamp with time zone null,
  constraint "FK_UserRecipePrefs_Households_HouseholdId"
    foreign key ("HouseholdId") references "Households" ("Id") on delete cascade,
  constraint "FK_UserRecipePrefs_Recipes_RecipeId"
    foreign key ("RecipeId") references "Recipes" ("Id") on delete cascade
);

create table if not exists "UserIngredientPrefs" (
  "Id" integer generated by default as identity primary key,
  "UserId" integer not null,
  "IngredientId" integer not null,
  "IsFavorite" boolean not null,
  "LastUsedAt" timestamp with time zone null,
  constraint "FK_UserIngredientPrefs_Ingredients_IngredientId"
    foreign key ("IngredientId") references "Ingredients" ("Id") on delete cascade,
  constraint "FK_UserIngredientPrefs_Users_UserId"
    foreign key ("UserId") references "Users" ("Id") on delete cascade
);

create table if not exists "UserWeekPrefs" (
  "Id" integer generated by default as identity primary key,
  "UserId" integer not null,
  "WeekId" integer not null,
  "IsFavorite" boolean not null,
  constraint "FK_UserWeekPrefs_Users_UserId"
    foreign key ("UserId") references "Users" ("Id") on delete cascade,
  constraint "FK_UserWeekPrefs_Weeks_WeekId"
    foreign key ("WeekId") references "Weeks" ("Id") on delete cascade
);

create table if not exists "GroceryLists" (
  "Id" integer generated by default as identity primary key,
  "WeekId" integer not null,
  "HouseholdId" integer not null,
  "GeneratedAt" timestamp with time zone not null,
  "Status" text not null,
  "CompletedAt" timestamp with time zone null,
  constraint "FK_GroceryLists_Households_HouseholdId"
    foreign key ("HouseholdId") references "Households" ("Id") on delete cascade,
  constraint "FK_GroceryLists_Weeks_WeekId"
    foreign key ("WeekId") references "Weeks" ("Id") on delete cascade
);

create table if not exists "PrepSheets" (
  "Id" integer generated by default as identity primary key,
  "WeekId" integer not null,
  "PrepDay" date not null,
  "SheetType" text not null,
  "GeneratedAt" timestamp with time zone not null,
  "TotalTimeMinutes" integer not null,
  constraint "FK_PrepSheets_Weeks_WeekId"
    foreign key ("WeekId") references "Weeks" ("Id") on delete cascade
);

create table if not exists "SnackSuggestions" (
  "Id" integer generated by default as identity primary key,
  "WeekId" integer not null,
  "DayOfWeek" text not null,
  "SuggestionText" text not null,
  "FoodGroupTarget" text not null,
  "UsesFridgeItemId" integer null,
  "IsAccepted" boolean not null,
  "CreatedAt" timestamp with time zone not null,
  constraint "FK_SnackSuggestions_Weeks_WeekId"
    foreign key ("WeekId") references "Weeks" ("Id") on delete cascade
);

create table if not exists "WeekMealSlots" (
  "Id" integer generated by default as identity primary key,
  "WeekId" integer not null,
  "RecipeId" integer null,
  "DayOfWeek" text not null,
  "MealType" text not null,
  "IsEatingOut" boolean not null,
  "IsSkipped" boolean not null,
  "IsLocked" boolean not null,
  "ServingsPlanned" integer not null,
  "AssumedCompleted" boolean not null,
  "MarkedSkippedAt" timestamp with time zone null,
  constraint "FK_WeekMealSlots_Recipes_RecipeId"
    foreign key ("RecipeId") references "Recipes" ("Id") on delete set null,
  constraint "FK_WeekMealSlots_Weeks_WeekId"
    foreign key ("WeekId") references "Weeks" ("Id") on delete cascade
);

create table if not exists "GroceryListItems" (
  "Id" integer generated by default as identity primary key,
  "GroceryListId" integer not null,
  "IngredientId" integer not null,
  "PlannedQuantity" numeric not null,
  "PlannedUnit" text not null,
  "PurchasedQuantity" numeric null,
  "StoreSection" text not null,
  "IsChecked" boolean not null,
  "AddedToFridge" boolean not null,
  "RecipeIds" jsonb not null,
  constraint "FK_GroceryListItems_GroceryLists_GroceryListId"
    foreign key ("GroceryListId") references "GroceryLists" ("Id") on delete cascade,
  constraint "FK_GroceryListItems_Ingredients_IngredientId"
    foreign key ("IngredientId") references "Ingredients" ("Id") on delete cascade
);

create table if not exists "PrepSheetSteps" (
  "Id" integer generated by default as identity primary key,
  "PrepSheetId" integer not null,
  "RecipeStepId" integer not null,
  "DisplayOrder" integer not null,
  "ParallelGroup" integer not null,
  "StartOffsetMinutes" integer not null,
  "RecipeNameContext" text not null,
  constraint "FK_PrepSheetSteps_PrepSheets_PrepSheetId"
    foreign key ("PrepSheetId") references "PrepSheets" ("Id") on delete cascade,
  constraint "FK_PrepSheetSteps_RecipeSteps_RecipeStepId"
    foreign key ("RecipeStepId") references "RecipeSteps" ("Id") on delete cascade
);

create table if not exists "FridgeDepletionLogs" (
  "Id" integer generated by default as identity primary key,
  "FridgeItemId" integer not null,
  "WeekMealSlotId" integer not null,
  "QuantityUsed" numeric not null,
  "DepletedAt" timestamp with time zone not null,
  "WasAssumed" boolean not null,
  "OverriddenByUser" boolean not null,
  constraint "FK_FridgeDepletionLogs_FridgeItems_FridgeItemId"
    foreign key ("FridgeItemId") references "FridgeItems" ("Id") on delete cascade,
  constraint "FK_FridgeDepletionLogs_WeekMealSlots_WeekMealSlotId"
    foreign key ("WeekMealSlotId") references "WeekMealSlots" ("Id") on delete restrict
);

create unique index if not exists "IX_HouseholdPreferences_HouseholdId"
  on "HouseholdPreferences" ("HouseholdId");

create index if not exists "IX_Recipes_HouseholdId"
  on "Recipes" ("HouseholdId");

create index if not exists "IX_Recipes_Cuisine"
  on "Recipes" ("Cuisine");

create unique index if not exists "IX_Users_Email"
  on "Users" ("Email");

create index if not exists "IX_Users_HouseholdId"
  on "Users" ("HouseholdId");

create index if not exists "IX_Weeks_HouseholdId"
  on "Weeks" ("HouseholdId");

create index if not exists "IX_FridgeItems_HouseholdId_ExpiresAt"
  on "FridgeItems" ("HouseholdId", "ExpiresAt");

create index if not exists "IX_FridgeItems_HouseholdId_Location"
  on "FridgeItems" ("HouseholdId", "Location");

create index if not exists "IX_FridgeItems_IngredientId"
  on "FridgeItems" ("IngredientId");

create index if not exists "IX_RecipeIngredients_IngredientId"
  on "RecipeIngredients" ("IngredientId");

create index if not exists "IX_RecipeIngredients_RecipeId"
  on "RecipeIngredients" ("RecipeId");

create unique index if not exists "IX_RecipeSteps_RecipeId_StepNumber"
  on "RecipeSteps" ("RecipeId", "StepNumber");

create unique index if not exists "IX_UserRecipePrefs_HouseholdId_RecipeId"
  on "UserRecipePrefs" ("HouseholdId", "RecipeId");

create index if not exists "IX_UserRecipePrefs_RecipeId"
  on "UserRecipePrefs" ("RecipeId");

create unique index if not exists "IX_UserIngredientPrefs_UserId_IngredientId"
  on "UserIngredientPrefs" ("UserId", "IngredientId");

create index if not exists "IX_UserIngredientPrefs_IngredientId"
  on "UserIngredientPrefs" ("IngredientId");

create unique index if not exists "IX_UserWeekPrefs_UserId_WeekId"
  on "UserWeekPrefs" ("UserId", "WeekId");

create index if not exists "IX_UserWeekPrefs_WeekId"
  on "UserWeekPrefs" ("WeekId");

create unique index if not exists "IX_GroceryLists_WeekId"
  on "GroceryLists" ("WeekId");

create index if not exists "IX_GroceryLists_HouseholdId"
  on "GroceryLists" ("HouseholdId");

create index if not exists "IX_PrepSheets_WeekId"
  on "PrepSheets" ("WeekId");

create index if not exists "IX_SnackSuggestions_WeekId"
  on "SnackSuggestions" ("WeekId");

create index if not exists "IX_WeekMealSlots_RecipeId"
  on "WeekMealSlots" ("RecipeId");

create unique index if not exists "IX_WeekMealSlots_WeekId_DayOfWeek_MealType"
  on "WeekMealSlots" ("WeekId", "DayOfWeek", "MealType");

create index if not exists "IX_GroceryListItems_GroceryListId"
  on "GroceryListItems" ("GroceryListId");

create index if not exists "IX_GroceryListItems_IngredientId"
  on "GroceryListItems" ("IngredientId");

create index if not exists "IX_PrepSheetSteps_PrepSheetId"
  on "PrepSheetSteps" ("PrepSheetId");

create index if not exists "IX_PrepSheetSteps_RecipeStepId"
  on "PrepSheetSteps" ("RecipeStepId");

create index if not exists "IX_FridgeDepletionLogs_FridgeItemId"
  on "FridgeDepletionLogs" ("FridgeItemId");

create index if not exists "IX_FridgeDepletionLogs_WeekMealSlotId"
  on "FridgeDepletionLogs" ("WeekMealSlotId");

create index if not exists "IX_Ingredients_Name"
  on "Ingredients" ("Name");

commit;
