begin;

create table if not exists "UserIngredientPrefs" (
  "Id" integer generated by default as identity primary key,
  "UserId" integer not null,
  "IngredientId" integer not null,
  "IsFavorite" boolean not null default false,
  "LastUsedAt" timestamp with time zone null,
  constraint "FK_UserIngredientPrefs_Ingredients_IngredientId"
    foreign key ("IngredientId") references "Ingredients" ("Id") on delete cascade,
  constraint "FK_UserIngredientPrefs_Users_UserId"
    foreign key ("UserId") references "Users" ("Id") on delete cascade
);

create unique index if not exists "IX_UserIngredientPrefs_UserId_IngredientId"
  on "UserIngredientPrefs" ("UserId", "IngredientId");

create index if not exists "IX_UserIngredientPrefs_IngredientId"
  on "UserIngredientPrefs" ("IngredientId");

create table if not exists "UserWeekPrefs" (
  "Id" integer generated by default as identity primary key,
  "UserId" integer not null,
  "WeekId" integer not null,
  "IsFavorite" boolean not null default false,
  constraint "FK_UserWeekPrefs_Users_UserId"
    foreign key ("UserId") references "Users" ("Id") on delete cascade,
  constraint "FK_UserWeekPrefs_Weeks_WeekId"
    foreign key ("WeekId") references "Weeks" ("Id") on delete cascade
);

create unique index if not exists "IX_UserWeekPrefs_UserId_WeekId"
  on "UserWeekPrefs" ("UserId", "WeekId");

create index if not exists "IX_UserWeekPrefs_WeekId"
  on "UserWeekPrefs" ("WeekId");

commit;
