// Recipe + ingredient names align with guides/seed_data/*.csv and guides/sql/supabase/03_seed_all_ingredients.sql
import { addDays, formatISO } from "date-fns";
import { getCurrentWeekStart, weekDays } from "./utils";
import type {
  FridgeItem,
  GroceryList,
  Ingredient,
  Recipe,
  SavedWeekTemplate,
  UserIngredientPref,
  UserRecipePref,
  UserWeekPref,
  Week,
  WeekMealSlot,
} from "types/models";

const baseWeekStart = getCurrentWeekStart();

export const mockWeek: Week = {
  id: 1,
  householdId: 1,
  weekStartDate: formatISO(baseWeekStart, { representation: "date" }),
  status: "Open",
  prepStyle: "OnePrepDay",
  maxCookTime: "Under45",
  isSavedTemplate: false,
  templateName: null,
  isInRotation: true,
  createdAt: new Date().toISOString(),
};

export const mockRecipes: Recipe[] = [
  {
    id: 1,
    householdId: 1,
    name: "Herby Chickpea Bowls",
    cuisine: "Mediterranean",
    scalabilityTag: "Flexible",
    timeTag: "Quick",
    prepStyleTag: "BatchFriendly",
    isFreezerFriendly: false,
    isCookFreshOnly: false,
    baseYieldServings: 4,
    mealTypeTags: ["Lunch", "Dinner"],
    imageUrl: null,
    sourceUrl: null,
    foodGroupServings: { Protein: 1, Vegetable: 2, Grains: 1 },
    createdAt: new Date().toISOString(),
    ingredients: [
      {
        id: 1,
        ingredientId: 1,
        ingredientName: "Baby spinach",
        quantity: 2,
        unit: "cups",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
      {
        id: 2,
        ingredientId: 3,
        ingredientName: "Brown rice",
        quantity: 1,
        unit: "cup",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
      {
        id: 12,
        ingredientId: 12,
        ingredientName: "Chickpeas",
        quantity: 1,
        unit: "can",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
      {
        id: 13,
        ingredientId: 13,
        ingredientName: "Lemon",
        quantity: 1,
        unit: "whole",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
      {
        id: 14,
        ingredientId: 14,
        ingredientName: "Garlic",
        quantity: 1,
        unit: "head",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
    ],
    steps: [
      {
        id: 1,
        stepNumber: 1,
        instruction: "Roast the chickpeas until crisp.",
        timingTag: "PrepAhead",
        durationMinutes: 20,
        isPassive: true,
      },
      {
        id: 2,
        stepNumber: 2,
        instruction: "Toss with herbs, lemon, and warm grains.",
        timingTag: "DayOfActive",
        durationMinutes: 10,
        isPassive: false,
      },
    ],
  },
  {
    id: 2,
    householdId: 1,
    name: "Tomato Butter Pasta",
    cuisine: "Italian",
    scalabilityTag: "Portioned",
    timeTag: "Medium",
    prepStyleTag: "CookFresh",
    isFreezerFriendly: false,
    isCookFreshOnly: true,
    baseYieldServings: 3,
    mealTypeTags: ["Lunch", "Dinner"],
    imageUrl: null,
    sourceUrl: null,
    foodGroupServings: { Grains: 2, Vegetable: 2 },
    createdAt: new Date().toISOString(),
    ingredients: [
      {
        id: 15,
        ingredientId: 15,
        ingredientName: "Macaroni",
        quantity: 12,
        unit: "oz",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
      {
        id: 16,
        ingredientId: 16,
        ingredientName: "Crushed Tomatoes",
        quantity: 1,
        unit: "can",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
      {
        id: 17,
        ingredientId: 17,
        ingredientName: "Butter",
        quantity: 4,
        unit: "tbsp",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
      {
        id: 18,
        ingredientId: 14,
        ingredientName: "Garlic",
        quantity: 4,
        unit: "cloves",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
    ],
    steps: [
      {
        id: 3,
        stepNumber: 1,
        instruction: "Simmer crushed tomatoes, butter, and garlic until glossy.",
        timingTag: "DayOfPassive",
        durationMinutes: 20,
        isPassive: true,
      },
      {
        id: 36,
        stepNumber: 2,
        instruction: "Cook macaroni until al dente, toss with the tomato butter sauce, and finish with salt and pepper.",
        timingTag: "DayOfActive",
        durationMinutes: 12,
        isPassive: false,
      },
    ],
  },
  {
    id: 3,
    householdId: 1,
    name: "Avocado Toast",
    cuisine: "American",
    scalabilityTag: "Flexible",
    timeTag: "Quick",
    prepStyleTag: "CookFresh",
    isFreezerFriendly: false,
    isCookFreshOnly: true,
    baseYieldServings: 1,
    mealTypeTags: ["Breakfast", "Lunch", "Snack"],
    imageUrl: null,
    sourceUrl: null,
    foodGroupServings: { Grains: 1, Fruit: 0.5, Protein: 0.5 },
    createdAt: new Date().toISOString(),
    ingredients: [
      {
        id: 4,
        ingredientId: 4,
        ingredientName: "Multigrain Bread",
        quantity: 1,
        unit: "slice",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
      {
        id: 5,
        ingredientId: 5,
        ingredientName: "Avocado",
        quantity: 1,
        unit: "half",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
      {
        id: 6,
        ingredientId: 6,
        ingredientName: "Eggs",
        quantity: 1,
        unit: "each",
        isModifier: true,
        isOptional: true,
        substituteIngredientIds: [],
        notes: "Popular add-on for extra protein.",
      },
      {
        id: 7,
        ingredientId: 7,
        ingredientName: "Bacon",
        quantity: 2,
        unit: "slices",
        isModifier: true,
        isOptional: true,
        substituteIngredientIds: [],
      },
      {
        id: 8,
        ingredientId: 8,
        ingredientName: "Cottage cheese",
        quantity: 0.25,
        unit: "cup",
        isModifier: true,
        isOptional: true,
        substituteIngredientIds: [],
      },
      {
        id: 9,
        ingredientId: 9,
        ingredientName: "Pico de gallo",
        quantity: 2,
        unit: "tbsp",
        isModifier: true,
        isOptional: true,
        substituteIngredientIds: [],
      },
      {
        id: 10,
        ingredientId: 10,
        ingredientName: "Balsamic Vinegar",
        quantity: 1,
        unit: "tsp",
        isModifier: true,
        isOptional: true,
        substituteIngredientIds: [],
      },
      {
        id: 11,
        ingredientId: 11,
        ingredientName: "Dried basil",
        quantity: 1,
        unit: "tsp",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
    ],
    steps: [
      {
        id: 31,
        stepNumber: 1,
        instruction: "Soft-boil eggs up to a day ahead if using: simmer 6 minutes, ice bath, peel when cool (or use pre-cooked eggs).",
        timingTag: "PrepAhead",
        durationMinutes: 14,
        isPassive: true,
      },
      {
        id: 32,
        stepNumber: 2,
        instruction: "Halve the avocado, remove pit, and scoop flesh into a bowl with a squeeze of lemon, flaky salt, and pepper. Mash to your texture (chunky or smooth).",
        timingTag: "PrepAhead",
        durationMinutes: 5,
        isPassive: false,
      },
      {
        id: 33,
        stepNumber: 3,
        instruction: "Toast bread until deeply golden and crisp on both sides (skillet with a little oil or a toaster).",
        timingTag: "DayOfActive",
        durationMinutes: 4,
        isPassive: false,
      },
      {
        id: 34,
        stepNumber: 4,
        instruction: "Spread the avocado over the toast edge to edge. Tear basil leaves on top.",
        timingTag: "DayOfActive",
        durationMinutes: 2,
        isPassive: false,
      },
      {
        id: 35,
        stepNumber: 5,
        instruction: "Warm crisp bacon or sliced egg if using; layer on top. Finish with flaky salt, pepper, and a drizzle of balsamic glaze or pico de gallo.",
        timingTag: "DayOfActive",
        durationMinutes: 5,
        isPassive: false,
      },
    ],
  },
  {
    id: 4,
    householdId: 1,
    name: "Chicken & Broccoli Jasmine Bowl",
    cuisine: "Asian",
    scalabilityTag: "Flexible",
    timeTag: "Medium",
    prepStyleTag: "CookFresh",
    isFreezerFriendly: false,
    isCookFreshOnly: false,
    baseYieldServings: 4,
    mealTypeTags: ["Lunch", "Dinner"],
    imageUrl: null,
    sourceUrl: null,
    foodGroupServings: { Protein: 2, Vegetable: 1, Grains: 1 },
    createdAt: new Date().toISOString(),
    ingredients: [
      {
        id: 19,
        ingredientId: 18,
        ingredientName: "Chicken Breast",
        quantity: 1.5,
        unit: "lb",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
      {
        id: 20,
        ingredientId: 19,
        ingredientName: "Broccoli",
        quantity: 1,
        unit: "head",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
      {
        id: 21,
        ingredientId: 20,
        ingredientName: "Jasmine Rice",
        quantity: 1.5,
        unit: "cups dry",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
      {
        id: 22,
        ingredientId: 39,
        ingredientName: "Soy Sauce",
        quantity: 3,
        unit: "tbsp",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
      {
        id: 23,
        ingredientId: 14,
        ingredientName: "Garlic",
        quantity: 3,
        unit: "cloves",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
      {
        id: 24,
        ingredientId: 37,
        ingredientName: "Onion",
        quantity: 0.5,
        unit: "cup chopped",
        isModifier: false,
        isOptional: true,
        substituteIngredientIds: [],
      },
      {
        id: 25,
        ingredientId: 38,
        ingredientName: "Olive Oil",
        quantity: 2,
        unit: "tbsp",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
    ],
    steps: [
      {
        id: 201,
        stepNumber: 1,
        instruction: "Marinate sliced chicken with soy sauce, garlic, and a splash of oil (15 minutes or overnight).",
        timingTag: "PrepAhead",
        durationMinutes: 15,
        isPassive: true,
      },
      {
        id: 202,
        stepNumber: 2,
        instruction: "Steam rice; stir-fry chicken until golden, add broccoli and onion, splash of soy, serve over rice.",
        timingTag: "DayOfActive",
        durationMinutes: 22,
        isPassive: false,
      },
    ],
  },
  {
    id: 5,
    householdId: 1,
    name: "Black Bean Tacos",
    cuisine: "Mexican",
    scalabilityTag: "Flexible",
    timeTag: "Quick",
    prepStyleTag: "CookFresh",
    isFreezerFriendly: false,
    isCookFreshOnly: true,
    baseYieldServings: 4,
    mealTypeTags: ["Lunch", "Dinner"],
    imageUrl: null,
    sourceUrl: null,
    foodGroupServings: { Legume: 2, Vegetable: 1, Grains: 2, Dairy: 1 },
    createdAt: new Date().toISOString(),
    ingredients: [
      {
        id: 26,
        ingredientId: 21,
        ingredientName: "Black Beans",
        quantity: 2,
        unit: "cans",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
      {
        id: 27,
        ingredientId: 22,
        ingredientName: "Corn Tortilla",
        quantity: 8,
        unit: "tortillas",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
      {
        id: 28,
        ingredientId: 23,
        ingredientName: "Bell Pepper",
        quantity: 1,
        unit: "cup chopped",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
      {
        id: 29,
        ingredientId: 24,
        ingredientName: "Cheddar Cheese",
        quantity: 6,
        unit: "oz shredded",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
      {
        id: 30,
        ingredientId: 25,
        ingredientName: "Cherry Tomatoes",
        quantity: 1,
        unit: "pint",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
      {
        id: 31,
        ingredientId: 29,
        ingredientName: "Green Onions",
        quantity: 0.25,
        unit: "cup chopped",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
    ],
    steps: [
      {
        id: 203,
        stepNumber: 1,
        instruction: "Warm beans with cumin-style seasoning; char tortillas in a dry skillet.",
        timingTag: "DayOfActive",
        durationMinutes: 12,
        isPassive: false,
      },
      {
        id: 204,
        stepNumber: 2,
        instruction: "Build tacos with peppers, tomatoes, cheese, and green onions.",
        timingTag: "DayOfActive",
        durationMinutes: 8,
        isPassive: false,
      },
    ],
  },
  {
    id: 6,
    householdId: 1,
    name: "Edamame Noodle Bowl",
    cuisine: "Asian",
    scalabilityTag: "Flexible",
    timeTag: "Quick",
    prepStyleTag: "CookFresh",
    isFreezerFriendly: false,
    isCookFreshOnly: true,
    baseYieldServings: 2,
    mealTypeTags: ["Lunch", "Dinner"],
    imageUrl: null,
    sourceUrl: null,
    foodGroupServings: { Grains: 1, Legume: 1, Vegetable: 1 },
    createdAt: new Date().toISOString(),
    ingredients: [
      {
        id: 32,
        ingredientId: 26,
        ingredientName: "Brown Rice Noodles",
        quantity: 6,
        unit: "oz",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
      {
        id: 33,
        ingredientId: 27,
        ingredientName: "Edamame",
        quantity: 1,
        unit: "cup shelled",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
      {
        id: 34,
        ingredientId: 28,
        ingredientName: "Kale",
        quantity: 2,
        unit: "cups chopped",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
      {
        id: 35,
        ingredientId: 29,
        ingredientName: "Green Onions",
        quantity: 3,
        unit: "tbsp sliced",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
      {
        id: 36,
        ingredientId: 39,
        ingredientName: "Soy Sauce",
        quantity: 2,
        unit: "tbsp",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
      {
        id: 56,
        ingredientId: 38,
        ingredientName: "Olive Oil",
        quantity: 1,
        unit: "tbsp",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
    ],
    steps: [
      {
        id: 205,
        stepNumber: 1,
        instruction: "Cook noodles, toss with edamame, kale, and a quick soy pan sauce.",
        timingTag: "DayOfActive",
        durationMinutes: 15,
        isPassive: false,
      },
    ],
  },
  {
    id: 7,
    householdId: 1,
    name: "Peach Yogurt Parfait",
    cuisine: "American",
    scalabilityTag: "Portioned",
    timeTag: "Quick",
    prepStyleTag: "CookFresh",
    isFreezerFriendly: false,
    isCookFreshOnly: true,
    baseYieldServings: 2,
    mealTypeTags: ["Breakfast", "Snack"],
    imageUrl: null,
    sourceUrl: null,
    foodGroupServings: { Dairy: 1, Fruit: 1, Grains: 1 },
    createdAt: new Date().toISOString(),
    ingredients: [
      {
        id: 38,
        ingredientId: 2,
        ingredientName: "Greek yogurt",
        quantity: 2,
        unit: "cups",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
      {
        id: 39,
        ingredientId: 30,
        ingredientName: "Granola",
        quantity: 1,
        unit: "cup",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
      {
        id: 40,
        ingredientId: 31,
        ingredientName: "Canned Peaches",
        quantity: 1,
        unit: "cup drained",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
    ],
    steps: [
      {
        id: 206,
        stepNumber: 1,
        instruction: "Layer yogurt, peaches, and granola in jars or bowls.",
        timingTag: "DayOfActive",
        durationMinutes: 5,
        isPassive: false,
      },
    ],
  },
  {
    id: 8,
    householdId: 1,
    name: "Sheet Pan Cod with Potatoes",
    cuisine: "American",
    scalabilityTag: "Rigid",
    timeTag: "Medium",
    prepStyleTag: "CookFresh",
    isFreezerFriendly: false,
    isCookFreshOnly: true,
    baseYieldServings: 3,
    mealTypeTags: ["Dinner"],
    imageUrl: null,
    sourceUrl: null,
    foodGroupServings: { Protein: 2, Vegetable: 1, Grains: 0.5 },
    createdAt: new Date().toISOString(),
    ingredients: [
      {
        id: 41,
        ingredientId: 32,
        ingredientName: "Cod",
        quantity: 1.25,
        unit: "lb",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
      {
        id: 42,
        ingredientId: 33,
        ingredientName: "Potato",
        quantity: 1,
        unit: "lb cubed",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
      {
        id: 43,
        ingredientId: 34,
        ingredientName: "Green Beans",
        quantity: 12,
        unit: "oz",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
      {
        id: 44,
        ingredientId: 38,
        ingredientName: "Olive Oil",
        quantity: 3,
        unit: "tbsp",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
      {
        id: 45,
        ingredientId: 13,
        ingredientName: "Lemon",
        quantity: 0.5,
        unit: "whole",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
    ],
    steps: [
      {
        id: 207,
        stepNumber: 1,
        instruction: "Toss potatoes and green beans with oil, salt, and pepper; roast at 425°F for 18 minutes.",
        timingTag: "DayOfActive",
        durationMinutes: 18,
        isPassive: true,
      },
      {
        id: 208,
        stepNumber: 2,
        instruction: "Nest cod on the pan, brush with lemon, roast until fish flakes.",
        timingTag: "DayOfActive",
        durationMinutes: 10,
        isPassive: true,
      },
    ],
  },
  {
    id: 9,
    householdId: 1,
    name: "Quick Naan Margherita",
    cuisine: "Italian",
    scalabilityTag: "Flexible",
    timeTag: "Quick",
    prepStyleTag: "CookFresh",
    isFreezerFriendly: false,
    isCookFreshOnly: true,
    baseYieldServings: 2,
    mealTypeTags: ["Lunch", "Snack"],
    imageUrl: null,
    sourceUrl: null,
    foodGroupServings: { Grains: 1, Dairy: 1, Vegetable: 1 },
    createdAt: new Date().toISOString(),
    ingredients: [
      {
        id: 71,
        ingredientId: 35,
        ingredientName: "Naan",
        quantity: 2,
        unit: "pieces",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
      {
        id: 72,
        ingredientId: 16,
        ingredientName: "Crushed Tomatoes",
        quantity: 0.75,
        unit: "cup",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
      {
        id: 73,
        ingredientId: 36,
        ingredientName: "Parmesan Cheese",
        quantity: 2,
        unit: "oz grated",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
      {
        id: 74,
        ingredientId: 11,
        ingredientName: "Dried basil",
        quantity: 0.5,
        unit: "tsp",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
    ],
    steps: [
      {
        id: 209,
        stepNumber: 1,
        instruction: "Toast naan, spread warm crushed tomatoes, top with parmesan and basil.",
        timingTag: "DayOfActive",
        durationMinutes: 10,
        isPassive: false,
      },
    ],
  },
];

const mealRotation = [1, 2, 3, 4, 5, 6, 7, 8, 9, null];

export const mockSlots: WeekMealSlot[] = weekDays.flatMap((day, index) =>
  (["Breakfast", "Lunch", "Dinner", "Snack"] as const).map((mealType, mealIndex) => {
    const recipeId = mealRotation[(index + mealIndex) % mealRotation.length];
    const recipe = mockRecipes.find((entry) => entry.id === recipeId);
    const planDate = formatISO(addDays(baseWeekStart, index), { representation: "date" });

    return {
      id: index * 10 + mealIndex + 1,
      weekId: 1,
      planDate,
      recipeId,
      recipeName: recipe?.name ?? null,
      selectedModifierIngredientIds: [],
      dayOfWeek: day,
      mealType: mealType as WeekMealSlot["mealType"],
      position: 0,
      isEatingOut: false,
      isSkipped: false,
      isLocked: false,
      servingsPlanned: 2,
      assumedCompleted: false,
      markedSkippedAt: null,
    };
  }),
);

function templateSlotsFromMockSlots(): SavedWeekTemplate["slots"] {
  return mockSlots.map((s) => ({
    dayOfWeek: s.dayOfWeek,
    mealType: s.mealType,
    position: s.position,
    recipeId: s.recipeId ?? null,
    recipeName: s.recipeName ?? null,
    isEatingOut: s.isEatingOut,
    isSkipped: s.isSkipped,
  }));
}

export const mockSavedTemplates: SavedWeekTemplate[] = [
  {
    id: 2,
    householdId: 1,
    name: "Cozy Spring Rotation",
    createdAt: new Date().toISOString(),
    slots: templateSlotsFromMockSlots().map((s, i) => (i % 5 === 0 ? { ...s, recipeId: 1, recipeName: "Herby Chickpea Bowls" } : s)),
  },
  {
    id: 3,
    householdId: 1,
    name: "Busy Week Backup",
    createdAt: new Date().toISOString(),
    slots: templateSlotsFromMockSlots().map((s, i) => (i % 3 === 0 ? { ...s, recipeId: 2, recipeName: "Tomato Butter Pasta" } : { ...s, recipeId: null, recipeName: null })),
  },
];

export const mockGroceryList: GroceryList = {
  id: 1,
  weekId: 1,
  householdId: 1,
  generatedAt: new Date().toISOString(),
  status: "Active",
  completedAt: null,
  items: [
    {
      id: 1,
      groceryListId: 1,
      ingredientId: 1,
      ingredientName: "Baby spinach",
      plannedQuantity: 2,
      plannedUnit: "bags",
      purchasedQuantity: null,
      storeSection: "Produce",
      isChecked: false,
      addedToFridge: false,
      recipeIds: [1, 3],
    },
    {
      id: 2,
      groceryListId: 1,
      ingredientId: 2,
      ingredientName: "Greek yogurt",
      plannedQuantity: 1,
      plannedUnit: "tub",
      purchasedQuantity: 1,
      storeSection: "Dairy",
      isChecked: true,
      addedToFridge: true,
      recipeIds: [1],
    },
    {
      id: 3,
      groceryListId: 1,
      ingredientId: 3,
      ingredientName: "Brown rice",
      plannedQuantity: 1,
      plannedUnit: "bag",
      purchasedQuantity: null,
      storeSection: "Grains",
      isChecked: false,
      addedToFridge: false,
      recipeIds: [1],
    },
  ],
};

export const mockFridgeItems: FridgeItem[] = [
  {
    id: 1,
    householdId: 1,
    ingredientId: 1,
    ingredientName: "Baby spinach",
    quantity: 1,
    unit: "bag",
    location: "Fridge",
    purchasedAt: new Date().toISOString(),
    expiresAt: addDays(new Date(), 1).toISOString(),
    isLeftover: false,
    sourceRecipeId: null,
    addedVia: "Manual",
  },
  {
    id: 2,
    householdId: 1,
    ingredientId: 2,
    ingredientName: "Greek yogurt",
    quantity: 1,
    unit: "tub",
    location: "Fridge",
    purchasedAt: new Date().toISOString(),
    expiresAt: addDays(new Date(), 5).toISOString(),
    isLeftover: false,
    sourceRecipeId: null,
    addedVia: "GroceryList",
  },
  {
    id: 3,
    householdId: 1,
    ingredientId: 3,
    ingredientName: "Frozen peas",
    quantity: 1,
    unit: "bag",
    location: "Freezer",
    purchasedAt: new Date().toISOString(),
    expiresAt: null,
    isLeftover: false,
    sourceRecipeId: null,
    addedVia: "Manual",
  },
  {
    id: 4,
    householdId: 1,
    ingredientId: 3,
    ingredientName: "Brown rice",
    quantity: 2,
    unit: "lb",
    location: "Pantry",
    purchasedAt: new Date().toISOString(),
    expiresAt: addDays(new Date(), 200).toISOString(),
    isLeftover: false,
    sourceRecipeId: null,
    addedVia: "Manual",
  },
  {
    id: 5,
    householdId: 1,
    ingredientId: 1,
    ingredientName: "Baby spinach",
    quantity: 0.5,
    unit: "bag",
    location: "Pantry",
    purchasedAt: new Date().toISOString(),
    expiresAt: addDays(new Date(), 2).toISOString(),
    isLeftover: false,
    sourceRecipeId: null,
    addedVia: "GroceryList",
  },
];

export const mockIngredients: Ingredient[] = [
  {
    id: 1,
    name: "Baby spinach",
    foodGroup: "Vegetable",
    servingSize: 1,
    servingUnit: "cup",
    purchaseUnit: "bag",
    defaultLocation: "Fridge",
    storeSection: "Produce",
    isPerishable: true,
    isFlexibleGroup: false,
    shelfLifeDays: 4,
  },
  {
    id: 2,
    name: "Greek yogurt",
    foodGroup: "Dairy",
    servingSize: 0.75,
    servingUnit: "cup",
    purchaseUnit: "tub",
    defaultLocation: "Fridge",
    storeSection: "Dairy",
    isPerishable: true,
    isFlexibleGroup: false,
    shelfLifeDays: 7,
  },
  {
    id: 3,
    name: "Brown rice",
    foodGroup: "Grains",
    servingSize: 0.5,
    servingUnit: "cup",
    purchaseUnit: "bag",
    defaultLocation: "Pantry",
    storeSection: "Grains",
    isPerishable: false,
    isFlexibleGroup: false,
    shelfLifeDays: 180,
  },
  {
    id: 4,
    name: "Multigrain Bread",
    foodGroup: "Grains",
    servingSize: 1,
    servingUnit: "slice",
    purchaseUnit: "loaf",
    defaultLocation: "Pantry",
    storeSection: "Grains",
    isPerishable: false,
    isFlexibleGroup: false,
    shelfLifeDays: 7,
  },
  {
    id: 5,
    name: "Avocado",
    foodGroup: "Vegetable",
    servingSize: 1,
    servingUnit: "whole",
    purchaseUnit: "each",
    defaultLocation: "Fridge",
    storeSection: "Produce",
    isPerishable: true,
    isFlexibleGroup: false,
    shelfLifeDays: 5,
  },
  {
    id: 6,
    name: "Eggs",
    foodGroup: "Protein",
    servingSize: 1,
    servingUnit: "large egg",
    purchaseUnit: "dozen",
    defaultLocation: "Fridge",
    storeSection: "Protein",
    isPerishable: true,
    isFlexibleGroup: false,
    shelfLifeDays: 21,
  },
  {
    id: 7,
    name: "Bacon",
    foodGroup: "Protein",
    servingSize: 2,
    servingUnit: "slices",
    purchaseUnit: "package",
    defaultLocation: "Fridge",
    storeSection: "Protein",
    isPerishable: true,
    isFlexibleGroup: false,
    shelfLifeDays: 7,
  },
  {
    id: 8,
    name: "Cottage cheese",
    foodGroup: "Dairy",
    servingSize: 1,
    servingUnit: "cup",
    purchaseUnit: "tub",
    defaultLocation: "Fridge",
    storeSection: "Dairy",
    isPerishable: true,
    isFlexibleGroup: false,
    shelfLifeDays: 7,
  },
  {
    id: 9,
    name: "Pico de Gallo",
    foodGroup: "Vegetable",
    servingSize: 1,
    servingUnit: "cup",
    purchaseUnit: "container",
    defaultLocation: "Fridge",
    storeSection: "Pantry",
    isPerishable: true,
    isFlexibleGroup: false,
    shelfLifeDays: 5,
  },
  {
    id: 10,
    name: "Balsamic Vinegar",
    foodGroup: "Other",
    servingSize: 0,
    servingUnit: "tbsp",
    purchaseUnit: "bottle",
    defaultLocation: "Pantry",
    storeSection: "Pantry",
    isPerishable: false,
    isFlexibleGroup: false,
    shelfLifeDays: 730,
  },
  {
    id: 11,
    name: "Dried Basil",
    foodGroup: "Other",
    servingSize: 0,
    servingUnit: "tsp",
    purchaseUnit: "jar",
    defaultLocation: "Pantry",
    storeSection: "Pantry",
    isPerishable: false,
    isFlexibleGroup: false,
    shelfLifeDays: 730,
  },
  {
    id: 12,
    name: "Chickpeas",
    foodGroup: "Legume",
    servingSize: 0.5,
    servingUnit: "cup",
    purchaseUnit: "can",
    defaultLocation: "Pantry",
    storeSection: "Protein",
    isPerishable: false,
    isFlexibleGroup: true,
    shelfLifeDays: 730,
  },
  {
    id: 13,
    name: "Lemon",
    foodGroup: "Fruit",
    servingSize: 1,
    servingUnit: "whole",
    purchaseUnit: "each",
    defaultLocation: "Fridge",
    storeSection: "Produce",
    isPerishable: true,
    isFlexibleGroup: false,
    shelfLifeDays: 21,
  },
  {
    id: 14,
    name: "Garlic",
    foodGroup: "Vegetable",
    servingSize: 0.5,
    servingUnit: "cup cloves",
    purchaseUnit: "head",
    defaultLocation: "Fridge",
    storeSection: "Produce",
    isPerishable: true,
    isFlexibleGroup: false,
    shelfLifeDays: 60,
  },
  {
    id: 15,
    name: "Macaroni",
    foodGroup: "Grains",
    servingSize: 0.5,
    servingUnit: "cup cooked",
    purchaseUnit: "box",
    defaultLocation: "Pantry",
    storeSection: "Grains",
    isPerishable: false,
    isFlexibleGroup: false,
    shelfLifeDays: 365,
  },
  {
    id: 16,
    name: "Crushed Tomatoes",
    foodGroup: "Vegetable",
    servingSize: 1,
    servingUnit: "cup",
    purchaseUnit: "can",
    defaultLocation: "Pantry",
    storeSection: "Pantry",
    isPerishable: false,
    isFlexibleGroup: false,
    shelfLifeDays: 730,
  },
  {
    id: 17,
    name: "Butter",
    foodGroup: "Other",
    servingSize: 0,
    servingUnit: "tbsp",
    purchaseUnit: "box",
    defaultLocation: "Fridge",
    storeSection: "Pantry",
    isPerishable: true,
    isFlexibleGroup: false,
    shelfLifeDays: 90,
  },
  {
    id: 18,
    name: "Chicken Breast",
    foodGroup: "Protein",
    servingSize: 3,
    servingUnit: "oz",
    purchaseUnit: "lb",
    defaultLocation: "Fridge",
    storeSection: "Protein",
    isPerishable: true,
    isFlexibleGroup: false,
    shelfLifeDays: 3,
  },
  {
    id: 19,
    name: "Broccoli",
    foodGroup: "Vegetable",
    servingSize: 1,
    servingUnit: "cup chopped",
    purchaseUnit: "head",
    defaultLocation: "Fridge",
    storeSection: "Produce",
    isPerishable: true,
    isFlexibleGroup: false,
    shelfLifeDays: 7,
  },
  {
    id: 20,
    name: "Jasmine Rice",
    foodGroup: "Grains",
    servingSize: 0.5,
    servingUnit: "cup cooked",
    purchaseUnit: "bag",
    defaultLocation: "Pantry",
    storeSection: "Grains",
    isPerishable: false,
    isFlexibleGroup: false,
    shelfLifeDays: 365,
  },
  {
    id: 21,
    name: "Black Beans",
    foodGroup: "Legume",
    servingSize: 0.5,
    servingUnit: "cup",
    purchaseUnit: "can",
    defaultLocation: "Pantry",
    storeSection: "Protein",
    isPerishable: false,
    isFlexibleGroup: true,
    shelfLifeDays: 730,
  },
  {
    id: 22,
    name: "Corn Tortilla",
    foodGroup: "Grains",
    servingSize: 1,
    servingUnit: "tortilla",
    purchaseUnit: "package",
    defaultLocation: "Pantry",
    storeSection: "Grains",
    isPerishable: false,
    isFlexibleGroup: false,
    shelfLifeDays: 14,
  },
  {
    id: 23,
    name: "Bell Pepper",
    foodGroup: "Vegetable",
    servingSize: 1,
    servingUnit: "cup chopped",
    purchaseUnit: "each",
    defaultLocation: "Fridge",
    storeSection: "Produce",
    isPerishable: true,
    isFlexibleGroup: false,
    shelfLifeDays: 7,
  },
  {
    id: 24,
    name: "Cheddar Cheese",
    foodGroup: "Dairy",
    servingSize: 1.5,
    servingUnit: "oz",
    purchaseUnit: "block",
    defaultLocation: "Fridge",
    storeSection: "Dairy",
    isPerishable: true,
    isFlexibleGroup: false,
    shelfLifeDays: 21,
  },
  {
    id: 25,
    name: "Cherry Tomatoes",
    foodGroup: "Vegetable",
    servingSize: 1,
    servingUnit: "cup",
    purchaseUnit: "pint",
    defaultLocation: "Fridge",
    storeSection: "Produce",
    isPerishable: true,
    isFlexibleGroup: false,
    shelfLifeDays: 7,
  },
  {
    id: 26,
    name: "Brown Rice Noodles",
    foodGroup: "Grains",
    servingSize: 0.5,
    servingUnit: "cup cooked",
    purchaseUnit: "package",
    defaultLocation: "Pantry",
    storeSection: "Grains",
    isPerishable: false,
    isFlexibleGroup: false,
    shelfLifeDays: 365,
  },
  {
    id: 27,
    name: "Edamame",
    foodGroup: "Legume",
    servingSize: 0.5,
    servingUnit: "cup",
    purchaseUnit: "bag",
    defaultLocation: "Fridge",
    storeSection: "Protein",
    isPerishable: true,
    isFlexibleGroup: true,
    shelfLifeDays: 5,
  },
  {
    id: 28,
    name: "Kale",
    foodGroup: "Vegetable",
    servingSize: 2,
    servingUnit: "cups raw",
    purchaseUnit: "bunch",
    defaultLocation: "Fridge",
    storeSection: "Produce",
    isPerishable: true,
    isFlexibleGroup: false,
    shelfLifeDays: 7,
  },
  {
    id: 29,
    name: "Green Onions",
    foodGroup: "Vegetable",
    servingSize: 1,
    servingUnit: "cup chopped",
    purchaseUnit: "bunch",
    defaultLocation: "Fridge",
    storeSection: "Produce",
    isPerishable: true,
    isFlexibleGroup: false,
    shelfLifeDays: 7,
  },
  {
    id: 30,
    name: "Granola",
    foodGroup: "Grains",
    servingSize: 0.5,
    servingUnit: "cup",
    purchaseUnit: "bag",
    defaultLocation: "Pantry",
    storeSection: "Grains",
    isPerishable: false,
    isFlexibleGroup: false,
    shelfLifeDays: 180,
  },
  {
    id: 31,
    name: "Canned Peaches",
    foodGroup: "Fruit",
    servingSize: 0.5,
    servingUnit: "cup",
    purchaseUnit: "can",
    defaultLocation: "Pantry",
    storeSection: "Pantry",
    isPerishable: false,
    isFlexibleGroup: false,
    shelfLifeDays: 730,
  },
  {
    id: 32,
    name: "Cod",
    foodGroup: "Protein",
    servingSize: 3,
    servingUnit: "oz",
    purchaseUnit: "lb",
    defaultLocation: "Fridge",
    storeSection: "Protein",
    isPerishable: true,
    isFlexibleGroup: false,
    shelfLifeDays: 2,
  },
  {
    id: 33,
    name: "Potato",
    foodGroup: "Vegetable",
    servingSize: 1,
    servingUnit: "cup cooked",
    purchaseUnit: "each",
    defaultLocation: "Fridge",
    storeSection: "Produce",
    isPerishable: true,
    isFlexibleGroup: false,
    shelfLifeDays: 30,
  },
  {
    id: 34,
    name: "Green Beans",
    foodGroup: "Vegetable",
    servingSize: 1,
    servingUnit: "cup",
    purchaseUnit: "bag",
    defaultLocation: "Fridge",
    storeSection: "Produce",
    isPerishable: true,
    isFlexibleGroup: false,
    shelfLifeDays: 7,
  },
  {
    id: 35,
    name: "Naan",
    foodGroup: "Grains",
    servingSize: 1,
    servingUnit: "piece",
    purchaseUnit: "package",
    defaultLocation: "Pantry",
    storeSection: "Grains",
    isPerishable: false,
    isFlexibleGroup: false,
    shelfLifeDays: 7,
  },
  {
    id: 36,
    name: "Parmesan Cheese",
    foodGroup: "Dairy",
    servingSize: 1.5,
    servingUnit: "oz",
    purchaseUnit: "wedge",
    defaultLocation: "Fridge",
    storeSection: "Dairy",
    isPerishable: true,
    isFlexibleGroup: false,
    shelfLifeDays: 30,
  },
  {
    id: 37,
    name: "Onion",
    foodGroup: "Vegetable",
    servingSize: 1,
    servingUnit: "cup chopped",
    purchaseUnit: "each",
    defaultLocation: "Fridge",
    storeSection: "Produce",
    isPerishable: true,
    isFlexibleGroup: false,
    shelfLifeDays: 30,
  },
  {
    id: 38,
    name: "Olive Oil",
    foodGroup: "Other",
    servingSize: 0,
    servingUnit: "tbsp",
    purchaseUnit: "bottle",
    defaultLocation: "Pantry",
    storeSection: "Pantry",
    isPerishable: false,
    isFlexibleGroup: false,
    shelfLifeDays: 730,
  },
  {
    id: 39,
    name: "Soy Sauce",
    foodGroup: "Other",
    servingSize: 0,
    servingUnit: "tbsp",
    purchaseUnit: "bottle",
    defaultLocation: "Pantry",
    storeSection: "Pantry",
    isPerishable: false,
    isFlexibleGroup: false,
    shelfLifeDays: 730,
  },
];

/** @deprecated use mockSavedTemplates — kept for older imports during migration */
export const mockSavedWeeks: Week[] = mockSavedTemplates.map((t) => ({
  ...mockWeek,
  id: t.id,
  isSavedTemplate: true,
  templateName: t.name,
  isInRotation: t.id === 2,
}));

export const mockRecipePrefs: Record<number, UserRecipePref> = {
  1: {
    id: 1,
    recipeId: 1,
    isFavorite: true,
    isDisliked: false,
    selectedModifierIngredientIds: [],
    lastUsedAt: new Date().toISOString(),
  },
  3: {
    id: 2,
    recipeId: 3,
    isFavorite: false,
    isDisliked: false,
    selectedModifierIngredientIds: [7],
    lastUsedAt: new Date().toISOString(),
  },
};

export const mockIngredientPrefs: Record<number, UserIngredientPref> = {
  1: {
    id: 1,
    userId: 1,
    ingredientId: 1,
    isFavorite: true,
    lastUsedAt: new Date().toISOString(),
  },
  2: {
    id: 2,
    userId: 1,
    ingredientId: 2,
    isFavorite: true,
    lastUsedAt: new Date().toISOString(),
  },
};

export const mockWeekPrefs: Record<number, UserWeekPref> = {
  2: {
    id: 1,
    userId: 1,
    weekId: 2,
    isFavorite: true,
  },
};
