import { addDays, formatISO } from "date-fns";
import { getCurrentWeekStart, weekDays } from "./utils";
import type {
  FridgeItem,
  GroceryList,
  Ingredient,
  Recipe,
  SavedWeekTemplate,
  UserIngredientPref,
  UserRecipePref,
  UserWeekPref,
  Week,
  WeekMealSlot,
} from "types/models";

const baseWeekStart = getCurrentWeekStart();

export const mockWeek: Week = {
  id: 1,
  householdId: 1,
  weekStartDate: formatISO(baseWeekStart, { representation: "date" }),
  status: "Open",
  prepStyle: "OnePrepDay",
  maxCookTime: "Under45",
  isSavedTemplate: false,
  templateName: null,
  isInRotation: true,
  createdAt: new Date().toISOString(),
};

export const mockRecipes: Recipe[] = [
  {
    id: 1,
    householdId: 1,
    name: "Herby Chickpea Bowls",
    cuisine: "Mediterranean",
    scalabilityTag: "Flexible",
    timeTag: "Quick",
    prepStyleTag: "BatchFriendly",
    isFreezerFriendly: false,
    isCookFreshOnly: false,
    baseYieldServings: 4,
    mealTypeTags: ["Lunch", "Dinner"],
    imageUrl: null,
    sourceUrl: null,
    foodGroupServings: { Protein: 1, Vegetable: 2, Grains: 1 },
    createdAt: new Date().toISOString(),
    ingredients: [
      {
        id: 1,
        ingredientId: 1,
        ingredientName: "Baby spinach",
        quantity: 2,
        unit: "cups",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
      {
        id: 2,
        ingredientId: 3,
        ingredientName: "Brown rice",
        quantity: 1,
        unit: "cup",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
    ],
    steps: [
      {
        id: 1,
        stepNumber: 1,
        instruction: "Roast the chickpeas until crisp.",
        timingTag: "PrepAhead",
        durationMinutes: 20,
        isPassive: true,
      },
      {
        id: 2,
        stepNumber: 2,
        instruction: "Toss with herbs, lemon, and warm grains.",
        timingTag: "DayOfActive",
        durationMinutes: 10,
        isPassive: false,
      },
    ],
  },
  {
    id: 2,
    householdId: 1,
    name: "Tomato Butter Pasta",
    cuisine: "Italian",
    scalabilityTag: "Portioned",
    timeTag: "Medium",
    prepStyleTag: "CookFresh",
    isFreezerFriendly: false,
    isCookFreshOnly: true,
    baseYieldServings: 3,
    mealTypeTags: ["Lunch", "Dinner"],
    imageUrl: null,
    sourceUrl: null,
    foodGroupServings: { Grains: 2, Vegetable: 1 },
    createdAt: new Date().toISOString(),
    ingredients: [
      {
        id: 3,
        ingredientId: 3,
        ingredientName: "Brown rice",
        quantity: 0.5,
        unit: "cup",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
    ],
    steps: [
      {
        id: 3,
        stepNumber: 1,
        instruction: "Simmer tomatoes, butter, and garlic.",
        timingTag: "DayOfPassive",
        durationMinutes: 20,
        isPassive: true,
      },
    ],
  },
  {
    id: 3,
    householdId: 1,
    name: "Avocado Toast",
    cuisine: "American",
    scalabilityTag: "Flexible",
    timeTag: "Quick",
    prepStyleTag: "CookFresh",
    isFreezerFriendly: false,
    isCookFreshOnly: true,
    baseYieldServings: 1,
    mealTypeTags: ["Breakfast", "Lunch", "Snack"],
    imageUrl: null,
    sourceUrl: null,
    foodGroupServings: { Grains: 1, Fruit: 0.5, Protein: 0.5 },
    createdAt: new Date().toISOString(),
    ingredients: [
      {
        id: 4,
        ingredientId: 4,
        ingredientName: "Whole grain bread",
        quantity: 1,
        unit: "slice",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
      {
        id: 5,
        ingredientId: 5,
        ingredientName: "Avocado",
        quantity: 1,
        unit: "half",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
      {
        id: 6,
        ingredientId: 6,
        ingredientName: "Boiled egg",
        quantity: 1,
        unit: "each",
        isModifier: true,
        isOptional: true,
        substituteIngredientIds: [],
        notes: "Popular add-on for extra protein.",
      },
      {
        id: 7,
        ingredientId: 7,
        ingredientName: "Bacon",
        quantity: 2,
        unit: "slices",
        isModifier: true,
        isOptional: true,
        substituteIngredientIds: [],
      },
      {
        id: 8,
        ingredientId: 8,
        ingredientName: "Cottage cheese",
        quantity: 0.25,
        unit: "cup",
        isModifier: true,
        isOptional: true,
        substituteIngredientIds: [],
      },
      {
        id: 9,
        ingredientId: 9,
        ingredientName: "Pico de gallo",
        quantity: 2,
        unit: "tbsp",
        isModifier: true,
        isOptional: true,
        substituteIngredientIds: [],
      },
      {
        id: 10,
        ingredientId: 10,
        ingredientName: "Balsamic glaze",
        quantity: 1,
        unit: "tsp",
        isModifier: true,
        isOptional: true,
        substituteIngredientIds: [],
      },
      {
        id: 11,
        ingredientId: 11,
        ingredientName: "Fresh basil",
        quantity: 6,
        unit: "leaves",
        isModifier: false,
        isOptional: false,
        substituteIngredientIds: [],
      },
    ],
    steps: [
      {
        id: 31,
        stepNumber: 1,
        instruction: "Soft-boil eggs up to a day ahead if using: simmer 6 minutes, ice bath, peel when cool (or use pre-cooked eggs).",
        timingTag: "PrepAhead",
        durationMinutes: 14,
        isPassive: true,
      },
      {
        id: 32,
        stepNumber: 2,
        instruction: "Halve the avocado, remove pit, and scoop flesh into a bowl with a squeeze of lemon, flaky salt, and pepper. Mash to your texture (chunky or smooth).",
        timingTag: "PrepAhead",
        durationMinutes: 5,
        isPassive: false,
      },
      {
        id: 33,
        stepNumber: 3,
        instruction: "Toast bread until deeply golden and crisp on both sides (skillet with a little oil or a toaster).",
        timingTag: "DayOfActive",
        durationMinutes: 4,
        isPassive: false,
      },
      {
        id: 34,
        stepNumber: 4,
        instruction: "Spread the avocado over the toast edge to edge. Tear basil leaves on top.",
        timingTag: "DayOfActive",
        durationMinutes: 2,
        isPassive: false,
      },
      {
        id: 35,
        stepNumber: 5,
        instruction: "Warm crisp bacon or sliced egg if using; layer on top. Finish with flaky salt, pepper, and a drizzle of balsamic glaze or pico de gallo.",
        timingTag: "DayOfActive",
        durationMinutes: 5,
        isPassive: false,
      },
    ],
  },
];

const mealRotation = [1, 2, null, 3];

export const mockSlots: WeekMealSlot[] = weekDays.flatMap((day, index) =>
  (["Breakfast", "Lunch", "Dinner", "Snack"] as const).map((mealType, mealIndex) => {
    const recipeId = mealRotation[(index + mealIndex) % mealRotation.length];
    const recipe = mockRecipes.find((entry) => entry.id === recipeId);
    const planDate = formatISO(addDays(baseWeekStart, index), { representation: "date" });

    return {
      id: index * 10 + mealIndex + 1,
      weekId: 1,
      planDate,
      recipeId,
      recipeName: recipe?.name ?? null,
      selectedModifierIngredientIds: [],
      dayOfWeek: day,
      mealType: mealType as WeekMealSlot["mealType"],
      position: 0,
      isEatingOut: false,
      isSkipped: false,
      isLocked: false,
      servingsPlanned: 2,
      assumedCompleted: false,
      markedSkippedAt: null,
    };
  }),
);

function templateSlotsFromMockSlots(): SavedWeekTemplate["slots"] {
  return mockSlots.map((s) => ({
    dayOfWeek: s.dayOfWeek,
    mealType: s.mealType,
    position: s.position,
    recipeId: s.recipeId ?? null,
    recipeName: s.recipeName ?? null,
    isEatingOut: s.isEatingOut,
    isSkipped: s.isSkipped,
  }));
}

export const mockSavedTemplates: SavedWeekTemplate[] = [
  {
    id: 2,
    householdId: 1,
    name: "Cozy Spring Rotation",
    createdAt: new Date().toISOString(),
    slots: templateSlotsFromMockSlots().map((s, i) => (i % 5 === 0 ? { ...s, recipeId: 1, recipeName: "Herby Chickpea Bowls" } : s)),
  },
  {
    id: 3,
    householdId: 1,
    name: "Busy Week Backup",
    createdAt: new Date().toISOString(),
    slots: templateSlotsFromMockSlots().map((s, i) => (i % 3 === 0 ? { ...s, recipeId: 2, recipeName: "Tomato Butter Pasta" } : { ...s, recipeId: null, recipeName: null })),
  },
];

export const mockGroceryList: GroceryList = {
  id: 1,
  weekId: 1,
  householdId: 1,
  generatedAt: new Date().toISOString(),
  status: "Active",
  completedAt: null,
  items: [
    {
      id: 1,
      groceryListId: 1,
      ingredientId: 1,
      ingredientName: "Baby spinach",
      plannedQuantity: 2,
      plannedUnit: "bags",
      purchasedQuantity: null,
      storeSection: "Produce",
      isChecked: false,
      addedToFridge: false,
      recipeIds: [1, 3],
    },
    {
      id: 2,
      groceryListId: 1,
      ingredientId: 2,
      ingredientName: "Greek yogurt",
      plannedQuantity: 1,
      plannedUnit: "tub",
      purchasedQuantity: 1,
      storeSection: "Dairy",
      isChecked: true,
      addedToFridge: true,
      recipeIds: [1],
    },
    {
      id: 3,
      groceryListId: 1,
      ingredientId: 3,
      ingredientName: "Brown rice",
      plannedQuantity: 1,
      plannedUnit: "bag",
      purchasedQuantity: null,
      storeSection: "Grains",
      isChecked: false,
      addedToFridge: false,
      recipeIds: [1],
    },
  ],
};

export const mockFridgeItems: FridgeItem[] = [
  {
    id: 1,
    householdId: 1,
    ingredientId: 1,
    ingredientName: "Baby spinach",
    quantity: 1,
    unit: "bag",
    location: "Fridge",
    purchasedAt: new Date().toISOString(),
    expiresAt: addDays(new Date(), 1).toISOString(),
    isLeftover: false,
    sourceRecipeId: null,
    addedVia: "Manual",
  },
  {
    id: 2,
    householdId: 1,
    ingredientId: 2,
    ingredientName: "Greek yogurt",
    quantity: 1,
    unit: "tub",
    location: "Fridge",
    purchasedAt: new Date().toISOString(),
    expiresAt: addDays(new Date(), 5).toISOString(),
    isLeftover: false,
    sourceRecipeId: null,
    addedVia: "GroceryList",
  },
  {
    id: 3,
    householdId: 1,
    ingredientId: 3,
    ingredientName: "Frozen peas",
    quantity: 1,
    unit: "bag",
    location: "Freezer",
    purchasedAt: new Date().toISOString(),
    expiresAt: null,
    isLeftover: false,
    sourceRecipeId: null,
    addedVia: "Manual",
  },
  {
    id: 4,
    householdId: 1,
    ingredientId: 3,
    ingredientName: "Brown rice",
    quantity: 2,
    unit: "lb",
    location: "Pantry",
    purchasedAt: new Date().toISOString(),
    expiresAt: addDays(new Date(), 200).toISOString(),
    isLeftover: false,
    sourceRecipeId: null,
    addedVia: "Manual",
  },
  {
    id: 5,
    householdId: 1,
    ingredientId: 1,
    ingredientName: "Baby spinach",
    quantity: 0.5,
    unit: "bag",
    location: "Pantry",
    purchasedAt: new Date().toISOString(),
    expiresAt: addDays(new Date(), 2).toISOString(),
    isLeftover: false,
    sourceRecipeId: null,
    addedVia: "GroceryList",
  },
];

export const mockIngredients: Ingredient[] = [
  {
    id: 1,
    name: "Baby spinach",
    foodGroup: "Vegetable",
    servingSize: 1,
    servingUnit: "cup",
    purchaseUnit: "bag",
    storeSection: "Produce",
    isPerishable: true,
    isFlexibleGroup: false,
    shelfLifeDays: 4,
  },
  {
    id: 2,
    name: "Greek yogurt",
    foodGroup: "Dairy",
    servingSize: 0.75,
    servingUnit: "cup",
    purchaseUnit: "tub",
    storeSection: "Dairy",
    isPerishable: true,
    isFlexibleGroup: false,
    shelfLifeDays: 7,
  },
  {
    id: 3,
    name: "Brown rice",
    foodGroup: "Grains",
    servingSize: 0.5,
    servingUnit: "cup",
    purchaseUnit: "bag",
    storeSection: "Grains",
    isPerishable: false,
    isFlexibleGroup: false,
    shelfLifeDays: 180,
  },
];

/** @deprecated use mockSavedTemplates — kept for older imports during migration */
export const mockSavedWeeks: Week[] = mockSavedTemplates.map((t) => ({
  ...mockWeek,
  id: t.id,
  isSavedTemplate: true,
  templateName: t.name,
  isInRotation: t.id === 2,
}));

export const mockRecipePrefs: Record<number, UserRecipePref> = {
  1: {
    id: 1,
    recipeId: 1,
    isFavorite: true,
    isDisliked: false,
    selectedModifierIngredientIds: [],
    lastUsedAt: new Date().toISOString(),
  },
  3: {
    id: 2,
    recipeId: 3,
    isFavorite: false,
    isDisliked: false,
    selectedModifierIngredientIds: [7],
    lastUsedAt: new Date().toISOString(),
  },
};

export const mockIngredientPrefs: Record<number, UserIngredientPref> = {
  1: {
    id: 1,
    userId: 1,
    ingredientId: 1,
    isFavorite: true,
    lastUsedAt: new Date().toISOString(),
  },
  2: {
    id: 2,
    userId: 1,
    ingredientId: 2,
    isFavorite: true,
    lastUsedAt: new Date().toISOString(),
  },
};

export const mockWeekPrefs: Record<number, UserWeekPref> = {
  2: {
    id: 1,
    userId: 1,
    weekId: 2,
    isFavorite: true,
  },
};
